version: "2"

run:
  timeout: 3m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - noctx
    - gosec
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*github.com/jmoiron/sqlx.DB).Close
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: unexported-return
          disabled: true
    exhaustive:
      default-signifies-exhaustive: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
      - path: mock_test\.go
        linters:
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
